// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jsxposed.x.core.bridge.shell_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ShellNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * shell 命令执行结果
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ShellResult (
  val exitCode: Long,
  val stdout: String,
  val stderr: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ShellResult {
      val exitCode = pigeonVar_list[0] as Long
      val stdout = pigeonVar_list[1] as String
      val stderr = pigeonVar_list[2] as String
      return ShellResult(exitCode, stdout, stderr)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      exitCode,
      stdout,
      stderr,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ShellResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return ShellNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ShellNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ShellResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ShellResult -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ShellNative {
  /**
   * 执行 shell 命令。
   *
   * [command] 完整 shell 命令（如 "pm list packages"）。
   * [useSu] 是否通过 `su -c` 以 root 权限执行。
   * [timeoutSeconds] 超时秒数（默认 30），超时后强制终止进程。
   */
  fun executeShell(command: String, useSu: Boolean, timeoutSeconds: Long, callback: (Result<ShellResult>) -> Unit)

  companion object {
    /** The codec used by ShellNative. */
    val codec: MessageCodec<Any?> by lazy {
      ShellNativePigeonCodec()
    }
    /** Sets up an instance of `ShellNative` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ShellNative?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ShellNative.executeShell$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val commandArg = args[0] as String
            val useSuArg = args[1] as Boolean
            val timeoutSecondsArg = args[2] as Long
            api.executeShell(commandArg, useSuArg, timeoutSecondsArg) { result: Result<ShellResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ShellNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ShellNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
