package com.jsxposed.x.feature.frida

import android.content.Context
import android.util.Log
import com.jsxposed.x.core.bridge.pinia_native.Pinia
import com.jsxposed.x.core.constants.PathConstant
import com.jsxposed.x.core.utils.shell.Shell

class FridaInjector(
    private val context: Context?,
    private val shell: Shell = Shell(su = true)
) {
    private companion object {
        private const val TAG = "FINDBUGS"
    }

    fun getFridaScripts(packageName: String): List<String> {
        return shell.getFileList(PathConstant.fridaProjectDirPath(packageName))
            .filter { it.endsWith(".js") }
            .filter {
                !it.endsWith("/hook.js") && !it.endsWith("hook.js") &&
                    !it.endsWith("/loader.js") && !it.endsWith("loader.js")
            }
    }

    fun buildHookScript(packageName: String): String? {
        val hookJsPath = PathConstant.fridaHookJsPath(packageName)
        Log.d(TAG, "Hook.js path: $hookJsPath")

        val allScripts = getFridaScripts(packageName)
        val enabledScripts = allScripts.filter { scriptPath ->
            val key = "frida_check_status_${packageName}_$scriptPath"
            if (context != null) {
                Pinia(context).getValue("pinia", key, false)
            } else {
                true
            }
        }

        if (enabledScripts.isEmpty()) {
            if (!shell.write("", hookJsPath)) {
                throw IllegalStateException("Unable to write $hookJsPath")
            }
            return hookJsPath
        }

        val builder = StringBuilder()
        builder.appendLine("// Auto-generated by JsXposed_X")
        builder.appendLine("// Contact us: https://muxue.pro")
        builder.appendLine("// https://github.com/dugongzi")
        builder.appendLine("// Package: $packageName")
        builder.appendLine("// Scripts: ${enabledScripts.size} enabled")
        builder.appendLine()
        builder.appendLine("Java.perform(function() {")
        builder.appendLine("    // ===== [Fx Sugar] =====")
        builder.appendLine(FridaSugar.CODE.prependIndent("    "))
        builder.appendLine()

        for (scriptPath in enabledScripts) {
            val content = shell.read(scriptPath)
            if (content.isEmpty() || content.startsWith("ERROR(") || content.startsWith("EXCEPTION:")) {
                continue
            }
            val displayName = scriptPath.substringAfterLast("/")
            val escapedName = displayName
                .replace("\\", "\\\\")
                .replace("'", "\\'")
            builder.appendLine("    // ===== [$displayName] =====")
            builder.appendLine("    (function() {")
            builder.appendLine("    var __jxScriptName = '$escapedName';")
            builder.appendLine("    var console = {")
            builder.appendLine("        log: function() { Fx._logWithScript(__jxScriptName, 'I', arguments); },")
            builder.appendLine("        info: function() { Fx._logWithScript(__jxScriptName, 'I', arguments); },")
            builder.appendLine("        debug: function() { Fx._logWithScript(__jxScriptName, 'D', arguments); },")
            builder.appendLine("        warn: function() { Fx._logWithScript(__jxScriptName, 'W', arguments); },")
            builder.appendLine("        error: function() { Fx._logWithScript(__jxScriptName, 'E', arguments); }")
            builder.appendLine("    };")
            builder.appendLine("    Fx._activeScript = __jxScriptName;")
            builder.appendLine("    try {")
            builder.appendLine(content.prependIndent("    "))
            builder.appendLine("    } catch(e) { console.error(e); }")
            builder.appendLine("    Fx._activeScript = null;")
            builder.appendLine("    })();")
            builder.appendLine()
        }

        builder.appendLine("});")
        val hookJsContent = builder.toString()
        if (!shell.write(hookJsContent, hookJsPath)) {
            throw IllegalStateException("Unable to write $hookJsPath")
        }
        return hookJsPath
    }
}
