// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jsxposed.x.core.bridge.project_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ProjectNativePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class AppInfo (
  val name: String,
  val packageName: String,
  val versionName: String,
  val versionCode: Long,
  val isSystemApp: Boolean,
  val icon: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AppInfo {
      val name = pigeonVar_list[0] as String
      val packageName = pigeonVar_list[1] as String
      val versionName = pigeonVar_list[2] as String
      val versionCode = pigeonVar_list[3] as Long
      val isSystemApp = pigeonVar_list[4] as Boolean
      val icon = pigeonVar_list[5] as ByteArray?
      return AppInfo(name, packageName, versionName, versionCode, isSystemApp, icon)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      packageName,
      versionName,
      versionCode,
      isSystemApp,
      icon,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AppInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return ProjectNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AuditLog (
  val algorithm: String,
  val operation: Long,
  val key: String,
  val keyBase64: String,
  val keyPlaintext: String,
  val iv: String? = null,
  val ivBase64: String? = null,
  val ivPlaintext: String? = null,
  val input: String,
  val inputBase64: String,
  val output: String,
  val outputBase64: String,
  val inputHex: String,
  val outputHex: String,
  val stackTrace: List<String?>,
  val fingerprint: String,
  val timestamp: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuditLog {
      val algorithm = pigeonVar_list[0] as String
      val operation = pigeonVar_list[1] as Long
      val key = pigeonVar_list[2] as String
      val keyBase64 = pigeonVar_list[3] as String
      val keyPlaintext = pigeonVar_list[4] as String
      val iv = pigeonVar_list[5] as String?
      val ivBase64 = pigeonVar_list[6] as String?
      val ivPlaintext = pigeonVar_list[7] as String?
      val input = pigeonVar_list[8] as String
      val inputBase64 = pigeonVar_list[9] as String
      val output = pigeonVar_list[10] as String
      val outputBase64 = pigeonVar_list[11] as String
      val inputHex = pigeonVar_list[12] as String
      val outputHex = pigeonVar_list[13] as String
      val stackTrace = pigeonVar_list[14] as List<String?>
      val fingerprint = pigeonVar_list[15] as String
      val timestamp = pigeonVar_list[16] as Long
      return AuditLog(algorithm, operation, key, keyBase64, keyPlaintext, iv, ivBase64, ivPlaintext, input, inputBase64, output, outputBase64, inputHex, outputHex, stackTrace, fingerprint, timestamp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      algorithm,
      operation,
      key,
      keyBase64,
      keyPlaintext,
      iv,
      ivBase64,
      ivPlaintext,
      input,
      inputBase64,
      output,
      outputBase64,
      inputHex,
      outputHex,
      stackTrace,
      fingerprint,
      timestamp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is AuditLog) {
      return false
    }
    if (this === other) {
      return true
    }
    return ProjectNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ProjectNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AppInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuditLog.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AppInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AuditLog -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ProjectNative {
  fun initProject(callback: (Result<Unit>) -> Unit)
  fun projectExists(packageName: String, callback: (Result<Boolean>) -> Unit)
  fun createProject(packageName: String, callback: (Result<Unit>) -> Unit)
  fun deleteProject(packageName: String, callback: (Result<Unit>) -> Unit)
  fun getProjects(callback: (Result<List<AppInfo>>) -> Unit)
  fun getFridaScripts(packageName: String, callback: (Result<List<String>>) -> Unit)
  fun createFridaScript(packageName: String, content: String, localPath: String, append: Boolean, callback: (Result<Unit>) -> Unit)
  fun readFridaScript(packageName: String, localPath: String, callback: (Result<String>) -> Unit)
  fun deleteFridaScript(packageName: String, scriptName: String, callback: (Result<Unit>) -> Unit)
  fun importFridaScripts(packageName: String, localPaths: List<String>, callback: (Result<Unit>) -> Unit)
  fun bundleFridaHookJs(packageName: String, callback: (Result<Unit>) -> Unit)
  fun getJsScripts(packageName: String, callback: (Result<List<String>>) -> Unit)
  fun createJsScript(packageName: String, content: String, localPath: String, append: Boolean, callback: (Result<Unit>) -> Unit)
  fun readJsScript(packageName: String, localPath: String, callback: (Result<String>) -> Unit)
  fun deleteJsScript(packageName: String, localPath: String, callback: (Result<Unit>) -> Unit)
  fun importJsScripts(packageName: String, localPaths: List<String>, callback: (Result<Unit>) -> Unit)
  fun getAuditLogs(packageName: String, limit: Long, offset: Long, keyword: String?, callback: (Result<List<AuditLog?>>) -> Unit)
  fun deleteAuditLog(packageName: String, timestamp: Long, callback: (Result<Unit>) -> Unit)
  fun updateAuditLog(packageName: String, updatedLog: AuditLog, callback: (Result<Unit>) -> Unit)
  fun clearAuditLogs(packageName: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by ProjectNative. */
    val codec: MessageCodec<Any?> by lazy {
      ProjectNativePigeonCodec()
    }
    /** Sets up an instance of `ProjectNative` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ProjectNative?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.initProject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initProject{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.projectExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.projectExists(packageNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProjectNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.createProject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.createProject(packageNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.deleteProject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.deleteProject(packageNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.getProjects$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getProjects{ result: Result<List<AppInfo>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProjectNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.getFridaScripts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.getFridaScripts(packageNameArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProjectNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.createFridaScript$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val contentArg = args[1] as String
            val localPathArg = args[2] as String
            val appendArg = args[3] as Boolean
            api.createFridaScript(packageNameArg, contentArg, localPathArg, appendArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.readFridaScript$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val localPathArg = args[1] as String
            api.readFridaScript(packageNameArg, localPathArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProjectNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.deleteFridaScript$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val scriptNameArg = args[1] as String
            api.deleteFridaScript(packageNameArg, scriptNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.importFridaScripts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val localPathsArg = args[1] as List<String>
            api.importFridaScripts(packageNameArg, localPathsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.bundleFridaHookJs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.bundleFridaHookJs(packageNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.getJsScripts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.getJsScripts(packageNameArg) { result: Result<List<String>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProjectNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.createJsScript$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val contentArg = args[1] as String
            val localPathArg = args[2] as String
            val appendArg = args[3] as Boolean
            api.createJsScript(packageNameArg, contentArg, localPathArg, appendArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.readJsScript$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val localPathArg = args[1] as String
            api.readJsScript(packageNameArg, localPathArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProjectNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.deleteJsScript$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val localPathArg = args[1] as String
            api.deleteJsScript(packageNameArg, localPathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.importJsScripts$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val localPathsArg = args[1] as List<String>
            api.importJsScripts(packageNameArg, localPathsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.getAuditLogs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val limitArg = args[1] as Long
            val offsetArg = args[2] as Long
            val keywordArg = args[3] as String?
            api.getAuditLogs(packageNameArg, limitArg, offsetArg, keywordArg) { result: Result<List<AuditLog?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ProjectNativePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.deleteAuditLog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val timestampArg = args[1] as Long
            api.deleteAuditLog(packageNameArg, timestampArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.updateAuditLog$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            val updatedLogArg = args[1] as AuditLog
            api.updateAuditLog(packageNameArg, updatedLogArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.JsxposedX.ProjectNative.clearAuditLogs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.clearAuditLogs(packageNameArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ProjectNativePigeonUtils.wrapError(error))
              } else {
                reply.reply(ProjectNativePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
