// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.jsxposed.x.core.bridge.desktop_bridge_native

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DesktopBridgeNativePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 桌面桥接请求参数
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DesktopBridgeRequest (
  val method: String,
  val params: Map<String, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DesktopBridgeRequest {
      val method = pigeonVar_list[0] as String
      val params = pigeonVar_list[1] as Map<String, Any?>?
      return DesktopBridgeRequest(method, params)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      method,
      params,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DesktopBridgeRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return DesktopBridgeNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * 桌面桥接响应结果
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DesktopBridgeResponse (
  val ok: Boolean,
  val result: Map<String, Any?>? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DesktopBridgeResponse {
      val ok = pigeonVar_list[0] as Boolean
      val result = pigeonVar_list[1] as Map<String, Any?>?
      val errorCode = pigeonVar_list[2] as String?
      val errorMessage = pigeonVar_list[3] as String?
      return DesktopBridgeResponse(ok, result, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ok,
      result,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DesktopBridgeResponse) {
      return false
    }
    if (this === other) {
      return true
    }
    return DesktopBridgeNativePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class DesktopBridgeNativePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DesktopBridgeRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DesktopBridgeResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DesktopBridgeRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DesktopBridgeResponse -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/**
 * 原生层调用 Dart 层处理桥接请求
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class DesktopBridgeFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DesktopBridgeFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      DesktopBridgeNativePigeonCodec()
    }
  }
  /** 处理来自桌面端的请求（项目管理、脚本执行、控制台等复杂操作） */
  fun handleRequest(requestArg: DesktopBridgeRequest, callback: (Result<DesktopBridgeResponse>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.JsxposedX.DesktopBridgeFlutterApi.handleRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(requestArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else if (it[0] == null) {
          callback(Result.failure(FlutterError("null-error", "Flutter api returned null value for non-null return value.", "")))
        } else {
          val output = it[0] as DesktopBridgeResponse
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(DesktopBridgeNativePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
